#ifndef QTROWRAPPER_H
#define QTROWRAPPER_H

#include <QObject>
#include <QSharedPointer>
#include <QWebSocket>
#include "websocketiodevice.h"
//This file is autogenerated from qto.rep
#include "rep_qtro_replica.h"
#include "qtrohelper.hpp"

class QtroWrapper : public QObject
{
    Q_OBJECT
public:
    explicit QtroWrapper(QString peerAddress, QObject *parent = nullptr);
    ~QtroWrapper();
    const QString autodiscoveryMessage = "FastECU_PTP_Autodiscovery";
    const QString remoteObjectName = "Test1";
    const int heartbeatInterval = 1000;

    long someFunc(QString s)
    {return qtrohelper::slot_sync(qtro_remote->someFunc(s));}
    int get_B()
    {return qtrohelper::slot_sync(qtro_remote->get_B());}
    bool set_B(int val)
    {qtrohelper::slot_sync(qtro_remote->set_B(val));return true;}

signals:
private:
    QString peerAddress;
    QWebSocket *webSocket;
    WebSocketIoDevice *socket;
    QSharedPointer<QtroRemoteReplica> qtro_remote;
    QRemoteObjectNode node;
    void startOverNetwok(void);
    void startLocal(void);
    void sendAutoDiscoveryMessage();
};

#endif // QTROWRAPPER_H
