#ifndef QTRO_HPP
#define QTRO_HPP
#include <QCoreApplication>
//This file is autogenerated from qtro.rep
#include "rep_qtro_source.h"

//Class QtroRemoteSimpleSource is autogenerated
class QtroRemote : public QtroRemoteSimpleSource
{
    Q_OBJECT
public:
    explicit QtroRemote(QObject *parent=nullptr)
        :QtroRemoteSimpleSource(parent)
        {qDebug() << "Server started";}
    ~QtroRemote()
        {qDebug() << "Server stopped";}
    //Class methods must be implemented
    //Getters and seeters for properties are autogenerated
    long someFunc(QString s) override
        {qDebug() << s; return 42;}
};

#endif // QTRO_HPP
